### ISSUE TITLE
.molang files are missing auto completion and are having color highlighting issues.

### ISSUE THREAD

**Issue by PavelDobCZ23** [Blockception/VSCode-Bedrock-Development-Extension#113]
**Describe the bug**
.`molang` files are missing any form of auto completion, color highlighting is present but is having issues as well.

**To Reproduce**

- Create a new `.molang` file.
- Open the file.
- Try to type start of a common function like `math.`
- There is no auto completion and color highlighting is messed up and malfunctioning.

**Expected behavior**
When trying to type a name of a common function like Molang queries/math functions and more, there should be an auto completion.

**Screenshots**
_Expected auto completion behavior, working within feature json file:_
![image](https://user-images.githubusercontent.com/62188082/132603385-d6e1febf-7002-4bb5-90e6-999f1fb38e99.png)

_Actual auto completion behavior within molang file and messed up color highlighting:_
![image](https://user-images.githubusercontent.com/62188082/132603745-037144bc-74a4-46fe-8b30-50b24328d69f.png)

**Comment by DaanV2** [comment]
Coming to version 2.1.55
