### ISSUE TITLE
Unexpected behavior of JSON formatter

### ISSUE THREAD

**Issue by Nusiq** [Blockception/VSCode-Bedrock-Development-Extension#12]
**Describe the bug**
Using the plugin seams to change the default JSON formatter to:
```
    "[json]": {
        "editor.defaultFormatter": "BlockceptionLtd.blockceptionvscodeminecraftbedrockdevelopmentextension"
    }
```
This setting causes unexpected behavior on "Format Document" operation - especially when the indentation
mode of the file is changed from tabs to spaces or the other way around.

Uninstalling the plugin fixed the problem for me. On first attempt of using "Format Document" I was asked
to select the default JSON formatter from a list with only one item.

The part of settings.json after selecting new formatter:
```
    "[json]": {
        "editor.defaultFormatter": "vscode.json-language-features"
    }
```

Reinstalling the plugin didn't bring back the bug so it's fixed for me.

**To Reproduce**

I don't know how to reproduce the change of the `json.editor.defaultFormatter`  setting (which seams to
happened to me with no reason by itself) but you can change the JSON formatter setting to the first
example and play around with changing indentation mode, number of spaces in the indent and
the "Format document" operator.

**Expected behavior**
- `defaultFormatter` shouldn't change without users consent.
- The blockception formater should be able to format document after changing the indentation mode.

**Additional context**
The same problem happened to other person who is also using the plugin and changing the
`defaultFormatter`  fixed the problem without need to reinstall the plugin.

The only plugin that I and the other person have in common on VS code is the Blockception's Minecraft Bedrock Development.

The probem was tested on Minecraft behavior file.

**Comment by DaanV2** [comment]
This is a problem of vscode itself and its interactions with the plugin. I have submitted a feature request with vscode for support of custom formatted able to target the specified files.

**Comment by DaanV2** [comment]
There is no formatter within the plugin that handles JSON files, just mcfunctions and language files.
however, when the plugin starts, it tells vscode what document it needs (or does changes to).

which are .mcfunction, .lang and .json files (as I need to parse json files for entities, sound etc).
so I made a formatted for .mcfunction and lang files. but I can only specify that there is 'a formatter' not a specific formatter for a specific file.

**Comment by Nusiq** [comment]
Ok I get it now. That makes sense.

The syntax of settings.json seams to support different settings for different file extensions. The code below shows what's currently in my config. Code formatter works for me both in json and lang.
```
    "[json]": {
        "editor.defaultFormatter": "vscode.json-language-features",
    },
    "[lang]": {
        "editor.defaultFormatter": "BlockceptionLtd.blockceptionvscodeminecraftbedrockdevelopmentextension"
    },
    "[mcfunction]": {
        "editor.defaultFormatter": "BlockceptionLtd.blockceptionvscodeminecraftbedrockdevelopmentextension"
    }
```
The formatter stops working when I'll add global formatter setting like this:
```
    "editor.defaultFormatter": "vscode.json-language-features",
    "[lang]": {
        "editor.defaultFormatter": "BlockceptionLtd.blockceptionvscodeminecraftbedrockdevelopmentextension"
    },
    "[mcfunction]": {
        "editor.defaultFormatter": "BlockceptionLtd.blockceptionvscodeminecraftbedrockdevelopmentextension"
    }
```

Off topic question - what does the formatter do for mcfunction?

**Comment by DaanV2** [comment]
I cant set settings unfortunately :/

The mcfunction formatter atm only format the following:

remove white space characters from the start and end of the command.
and just a couple of replaces such as:

`~+` -> `~`
`~+` -> `~`
`~0` -> `~`
`^+` -> `^`
`^0` -> `^`
`~~~` -> `~ ~ ~`

**Comment by DaanV2** [comment]
This has been fixed :)
