### ISSUE TITLE
"Blockception's Minecraft Bedrock Development" title in json file breadcrumbs

### ISSUE THREAD

**Issue by Nusiq** [Blockception/VSCode-Bedrock-Development-Extension#13]
**Describe the bug**
The "Blockception's Minecraft Bedrock Development" title is added to breadcrumbs in JSON files (see screenshots).
This title is quite long and it blocks the important information about current location of the cursor
in the json. 

**To Reproduce**
1. Enable breadcrumbs
2. Create json file (example uses custom block)
3. See the results.
Example file:
```
{
	"format_version": "1.16.0",
	"minecraft:block": {
		"description": {
			"identifier": "example:test_block",
			"is_experimental": false,
			"register_to_creative_menu": true
		},
		"components": {
			"minecraft:loot": "",
			"minecraft:destroy_time": 4.0,
			"minecraft:explosion_resistance": 5.0,
			"minecraft:map_color": "#f49d1a"
		}
	}
}
```

**Expected behavior**
Display information about json instead arbitrary title.

**Screenshots**
![obraz](https://user-images.githubusercontent.com/34062025/96255016-c2f83900-0fa5-11eb-84d4-e8c4b4828c1d.png)

**Comment by DaanV2** [comment]
I can't exactly fix this 100% as this is mostly a behavior of vscode itself 

I have included a possible workaround but its not certain it will fix for all occasions
