### ISSUE TITLE
[Feature Request] Ability to change the default file extensions when creating a file using a VSCode command

### ISSUE THREAD

**Issue by Mihro** [Blockception/VSCode-Bedrock-Development-Extension#133]
As an example, when using the command to create an entity or animation controller file, it creates `.entity.json` & `.controller.json` files respectively.

I prefer using the file extensions of `.e.json` & `.ac.json`, so when I use the command I have to manually rename the file each time.  
It would be great if there was a section in the VSCode extension settings that allows me to configure the automatic file extensions when creating a file using the commands.

I could just create the files manually or not change the file extensions but the latter isn't really a reasonable solution for me at the moment.

I imagine this could be done in the user `settings.json` (see below), or maybe in the actual Settings Editor.
```json
    "BC-MC.defaultFileExtensions": {
        "animationController": ".ac.json",
        "animation": ".anim.json",
        "entity": ".e.json",
        "geometry": ".geo.json"
    }
```

**Comment by DaanV2** [comment]
Solved with PR: #387
