### ISSUE TITLE
Diagnostics cannot be disabled

### ISSUE THREAD

**Issue by x-2mas** [Blockception/VSCode-Bedrock-Development-Extension#134]
Disabling diagnostic options in the extension settings isn't turning it off.

**Comment by DaanV2** [comment]
I have either fixed it in the new version, or you possibly need to reload the plugin after toggling it

**Comment by x-2mas** [comment]
The issue still persists unfortunately. 
I have tried restarting VS Code after changing settings but no luck.

Could it be multi-root workspaces that's causing this?

![Screenshot 2021-09-30 113632](https://user-images.githubusercontent.com/78643484/135396650-9f788ef5-797e-4ff5-970d-9da6278f04d7.png)
![Screenshot 2021-09-30 113518](https://user-images.githubusercontent.com/78643484/135396659-44ee609d-9344-4a4c-930b-174888ca44d9.png)

**Comment by DaanV2** [comment]
Hmm maybe could you check if your plugin is at the lastest version?

**Comment by DaanV2** [comment]
Also side note, I guess you want to disable it because of the vanilla files and the tags?

You can add missing tags to `.mcdefinitions` file: https://faq.blockception.dev/mcproject/mcdefinitions
You can add the names of the vanilla folders to the `.mcignore` file: https://faq.blockception.dev/mcproject/mcignore

But the plugin should now be aware of vanilla files itself

**Comment by DaanV2** [comment]
Tested it with multi-workspace but the settings are working for me in the latest version

**Comment by DaanV2** [comment]
Sorry I can't reproduce it, then, when you turned Diagnostics.enable off it shouldn't matter where the files are coming from it stops diagnostics

**Comment by DaanV2** [comment]
Wait are you opening a pre saved workspace?

**Comment by x-2mas** [comment]
Hmm... not sure what that is. It's a workspace I made myself.

**Comment by DaanV2** [comment]
have you saved it as a .code-workspace file?

**Comment by x-2mas** [comment]
yeah it saved to a workspace file

**Comment by x-2mas** [comment]
![Screenshot 2021-09-30 204337](https://user-images.githubusercontent.com/78643484/135482797-049ae855-ae49-40fb-885a-9b4f23472864.png)
these are my workspace and global settings for the extension

**Comment by DaanV2** [comment]
Pushing a new version, it might fix it, after that I can send you a separate version that might send more diagnostics information

**Comment by x-2mas** [comment]
It works fine now! Thank you!
I see you've reworked the the extension recently with new diagnosing features. That's neat. 

I'll let you know if I encounter any other major issues. :)

**Comment by DaanV2** [comment]
Its should also now work without vanilla files btw
