### ISSUE TITLE
Request textDocument/codeLens failed

### ISSUE THREAD

**Issue by BlueRains** [Blockception/VSCode-Bedrock-Development-Extension#142]
**Describe the bug**
Error in output:
Request textDocument/codeLens failed.
  Message: Request textDocument/codeLens failed with message: Invalid regular expression: /\b*\b/: Nothing to repeat
  Code: -32603 
In newest version (3.1.0)

**To Reproduce**
1. Install newest version
2. Open output

**Expected behavior**
Not giving errors

**Desktop:**
 - Windows 10
 - newest version VSCode
 - 3.1.0

**Additional context**
When I switched back to v3.0.19, the error disappeared.
I tested all 3.x versions, only 3.1.0 has this error.

**Comment by DaanV2** [comment]
Newest 3.1.1 should fix this
