### ISSUE TITLE
Fails to recognise molang functions v3.x

### ISSUE THREAD

**Issue by BlueRains** [Blockception/VSCode-Bedrock-Development-Extension#143]
**Describe the bug**
Blockception fails to recognize many molang functions and other things. It gives errors when none *should* exist. See screenshot for example. This only happens in version 3.x.x

**To Reproduce**
1. Download the vanilla behavior pack and/or resource pack
2. Open in VSCode with Blockception enabled
3. Open problems tab

**Expected behavior**
No problems existing

**Screenshots**

**Desktop:**
 - Windows
 - Newest version VSCode (1.60.2)

**Additional context**
This makes it almost impossible to detect when things are genuine problems.
![image](https://user-images.githubusercontent.com/83722494/135485913-549da0d4-b88b-4452-b286-c86843076690.png)

**Comment by DaanV2** [comment]
I went over these and all of these are actuall problems. I don't recommend adding the vanilla bp and rp to your workspace.

but if you do add them to the `.mcignore` file (https://faq.blockception.dev/mcproject/mcignore)

But other then that its indented behavior
