### ISSUE TITLE
Option to hide overlay text in editor

### ISSUE THREAD

**Issue by x-2mas** [Blockception/VSCode-Bedrock-Development-Extension#144]
This overlay hints/links (marked red in screenshot) are useful but tend to clutter the editor view. Can you include a setting to hide them? 

![Screenshot 2021-10-02 175840](https://user-images.githubusercontent.com/78643484/135716157-9b261153-e3a0-48cd-a56a-1320d8891d63.png)

**Comment by DaanV2** [comment]
Yes I can

**Comment by DaanV2** [comment]
Just as a note:

you can disable code lenses through the following:

```json
  "[bc-minecraft-language]": {
    "editor.insertSpaces": false,
    "editor.trimAutoWhitespace": false,
    "editor.codeLens": false
  },
  "[bc-mcfunction]": {
    "editor.codeLens": false
  },
```

**Comment by DaanV2** [comment]
Fixed in next version

**Comment by x-2mas** [comment]
Ah, they're called code lenses! Thank you! :)
