### ISSUE TITLE
No support for gametests in manifest

### ISSUE THREAD

**Issue by Paty007gr** [Blockception/VSCode-Bedrock-Development-Extension#148]
**Describe the bug**
the extension gives warnings about properties in the behavior pack's manifest.json file that minecraft is completely fine with

Warnings:
`entry` property in the gametest module is seen as not allowed or invalid
`javascript` value in the `type` property is also seen as an invalid module type
Pack versions below 1.0.0 like 0.1.0 or 0.0.1 are also seen as invalid

**To Reproduce**
By using the first manifest example on the gametest guide in bedrock.dev (https://wiki.bedrock.dev/scripting/game-tests.html#using-gametests) the warnings mentioned above appear

**Desktop Info:**
 - OS: Windows 10
 - Version: 3.1.21

**Comment by DaanV2** [comment]
About the version numbering, even though `[0, 0, 1]` is valid we do not support it as per marketplace convention your numbering has to start at 1.0.0

https://docs.microsoft.com/en-us/minecraft/creator/reference/content/addonsreference/examples/addonmanifest#modules
