### ISSUE TITLE
Extension uses excessive CPU

### ISSUE THREAD

**Issue by kyleplo** [Blockception/VSCode-Bedrock-Development-Extension#150]
**Describe the bug**
The extension has recently started using much more CPU than expected. It slowly builds up over time, after about 10 minutes it uses most of my CPU.

I have used the Extension Bisect feature to make sure this is an issue with this extension, not other extensions or VSCode itself.

**To Reproduce**
1. Open Task Manager/Activity Monitor
2. Use VSCode with the extension for like 10 minutes
3. Watch the CPU level of `Code Helper (Renderer)` go up

**Expected behavior**
The extension should not have such a big performance impact

**Desktop (please complete the following information):**
 - OS: macOS Big Sur 11.6
 - Browser N/A
 - Version N/A

**Smartphone (please complete the following information):**
 - Device: N/A
 - OS: N/A
 - Browser N/A
 - Version N/A

**Additional Context:**
Today (Oct 9, 2021) is the first time I've seen this issue, and I've been using the extension for several months

**Comment by DaanV2** [comment]
I cannot reproduce this, can you send me some additional information?

- Did you have an particular file open?
- And is the chat output looking good? 
- Could you send me a copy of the project.

**Comment by kyleplo** [comment]
This didn't seem to be related to a particular file. I didn't see anything in the output either.

**Comment by DaanV2** [comment]
Could be a optional bug with the filesystem that looks for file changes in vs code: https://github.com/Microsoft/vscode/issues/30959

Can you try that and see if this helps?

**Comment by DaanV2** [comment]
@kyleplo Sorry to ping you again, but I was wondering if you had a moment to check out the following fix:

```
@blargfoot that is weird, it seems to be the file watcher (weird because the folder you open is empty?). Does it reproduce if you configure: "files.useExperimentalFileWatcher": true and restart?
```
