### ISSUE TITLE
The hex code colors preview for transpartent particles uses RGBA format instead of ARGB

### ISSUE THREAD

**Issue by Nusiq** [Blockception/VSCode-Bedrock-Development-Extension#19]
**Describe the bug**
`minecraft:particle_appearance_tinting` is a particle component which tints color of particles. The particles that use "particles_blend" material can be semi transparent. Colors in the component can be described with
hex codes (#aabbccdd) which also gives a preview thatnks to the addon. Unfortunately the addon assumes
that the colors are in RGBA format which is wrong because minecraft uses ARGB.

**To Reproduce**
Use the code below to create a simple particle. It uses `particle_appearance_tinting` with #ffff00ff color.
The preview shows yellow because it thinks that its R=255, G=255, B=0, A=255 (yellow with no
transparency). The particle color in minecraft is magenta because R=255, G=0, B=255, A=255 (magenta
no transparency).

```
{
	"format_version": "1.10.0",
	"particle_effect": {
		"description": {
			"identifier": "nusiq:example",
			"basic_render_parameters": {
				"material": "particles_blend",
				"texture": "textures/particle/particles"
			}
		},
		"components": {
			"minecraft:emitter_rate_instant": {
				"num_particles": 1
			},
			"minecraft:emitter_lifetime_expression": {
				"activation_expression": 1,
				"expiration_expression": 0
			},
			"minecraft:emitter_shape_point": {},
			"minecraft:particle_lifetime_expression": {
				"expiration_expression": 0
			},
			"minecraft:particle_appearance_billboard": {
				"size": [1, 1],
				"facing_camera_mode": "lookat_xyz",
				"uv": {
					"texture_width": 128,
					"texture_height": 128,
					"flipbook": {
						"base_UV": [56, 88],
						"size_UV": [8, 8],
						"step_UV": [-8, 0],
						"frames_per_second": 8,
						"max_frame": 8,
						"stretch_to_lifetime": true,
						"loop": false
					}
				}
			},
			"minecraft:particle_appearance_tinting": {
				"color": "#ffff00ff"
			}
		}
	}
}
```

**Expected behavior**
The color preview should mach the color of particle.

**Screenshots**
![obraz](https://user-images.githubusercontent.com/34062025/97805168-5b501800-1c4c-11eb-9fdf-bd092b19d0b0.png)

**Additional context**
Passing colors as lists (which is also a valid input for the component) uses RGBA format - [1, 1, 0, 1] is yellow.

**Comment by DaanV2** [comment]
Unfortunately, I cannot do anything about this, the color support comes from vscode itself, I can only specify that it is a color in hex format :/
