### ISSUE TITLE
The "family" selector query doesn't show up in the autocompletion suggestion list

### ISSUE THREAD

**Issue by Nusiq** [Blockception/VSCode-Bedrock-Development-Extension#28]
**Describe the bug**
Recently a new selector query was added to minecraft - the "family". It lets you select entities by their families.

**To Reproduce**
1. Start typing any command that uses the selector.
2. See the list of suggested queries.
3. See that there is no "family" on the list.

**Expected behavior**
The "family" query should apear on the list.

**Screenshots**
![obraz](https://user-images.githubusercontent.com/34062025/102992950-2f4a6800-4514-11eb-98fb-9bf7edc4c6dc.png)

**Comment by DaanV2** [comment]
The family attribute has been added to the list of attributes for selectors, no auto complete for any values yet as the entities have to be parsed deeper than before to retrieve possible family components.
