### ISSUE TITLE
Invalid queries in selectors doesn't show an error

### ISSUE THREAD

**Issue by Nusiq** [Blockception/VSCode-Bedrock-Development-Extension#29]
**Describe the bug**
You can put invalid properties/queries in command selectors and it won't show any erros.

**To Reproduce**
Create following function and see that there is no error:
```
execute @e[random_property=1.23] ~ ~ ~ say hi
```

**Expected behavior**
The addon should allow only existing queries.

**Screenshots**
Minecraft shows error message when you try to run this command from chat:
![obraz](https://user-images.githubusercontent.com/34062025/102993269-bef01680-4514-11eb-9e5e-4991c242d6eb.png)

**Comment by DaanV2** [comment]
It doesn't do selector parsin yet, but putting it on the list

**Comment by DaanV2** [comment]
Selector diagnostics have been added :)
