### ISSUE TITLE
Add support for 1.17.0 / 1.17.40 minecraft version

### ISSUE THREAD

**Issue by ArpeggyDev** [Blockception/VSCode-Bedrock-Development-Extension#296]

**Comment by DaanV2** [comment]
Any specific document this is not the chase of?

**Comment by ArpeggyDev** [comment]
I mean, format versions 1.17.0 / 1.17.40 aren't supported yet. Could you add them please? I really love the extension but because of this issue I cant use it on that specific files :c
https://user-images.githubusercontent.com/93758976/149593818-8f16af7f-8031-45c6-88ef-269ae6956aad.mp4

And another suggestion: the extension detects the file when it is in the "resource_packs" or "behavior_packs" folder but when you develop add-ons, you mainly use the "development_resource_packs" and "development_behavior_packs" folders.

**Comment by ArpeggyDev** [comment]
I mean, format versions 1.17.0 / 1.17.40 aren't supported yet. Could you add them please? I really love the extension but because of this issue I cant use it on that specific files :c
https://user-images.githubusercontent.com/93758976/149593941-18c95d07-0206-45fc-afa1-f213ecc1b6a2.mp4


And another suggestion: the extension detects the file when it is in the "resource_packs" or "behavior_packs" folder but when you develop add-ons, you mainly use the "development_resource_packs" and "development_behavior_packs" folders.

**Comment by DaanV2** [comment]
Aah I see, The versions you are talking about are still experimental content, We cannot, unfortunately, spend the time to support experimental data formats :/

For the second thing I don't know where it would it fail, as the plugin looks if there is resource_packs in the filepath, thus if there is development_resource_packs there is resource_packs in it
