### ISSUE TITLE
[Feature Request] Generate any vanilla entity, item, block... file

### ISSUE THREAD

**Issue by DrAv0011** [Blockception/VSCode-Bedrock-Development-Extension#297]
When there is need to edit a vanilla file for a proyect we need to copy it from vanilla files. 
Being able to input a command to copy/generate it automatically would be great.

Idea is to have it similar to this command so we can search by tags and not the exact name
![image](https://user-images.githubusercontent.com/43525295/149629106-d9a2528d-78a3-4673-86ea-2c1246db49a5.png)

**Comment by DaanV2** [comment]
Sorry, I cannot add vanilla items as they are copyrighted. all files I generate are just templates
