### ISSUE TITLE
当我使用这个插件时，vscode无法正常更新

### ISSUE THREAD

**Issue by lchzh3473** [Blockception/VSCode-Bedrock-Development-Extension#30]
**Describe the bug**
当我使用这个插件时，vscode无法正常更新

**To Reproduce**
1. 正常使用时，提示vscode有更新可用，选择更新（图1），并等待后台安装
2. 等待完成（图2），选择“立即安装”
3. 出现“Updating Visual Studio Code”提示框（图3）
4. 不久之后出现如（图4）所示错误

**Expected behavior**
可能是因为文件名过长
在对应文件右键点击发现文件路径显示异常（图5）
与其他文件对比（图6）

**Screenshots**
图1
![image](https://user-images.githubusercontent.com/61674328/103168750-de6aa480-4870-11eb-9de6-d70b571cd5d8.png)
图2
![image](https://user-images.githubusercontent.com/61674328/103168640-e8d86e80-486f-11eb-8d9d-69debf4f3d4c.png)
图3
![image](https://user-images.githubusercontent.com/61674328/103168732-bb3ff500-4870-11eb-9619-d2e74c3b8e2e.png)
图4
![image](https://user-images.githubusercontent.com/61674328/103168806-66e94500-4871-11eb-89f2-b00886a5a672.png)
图5
![image](https://user-images.githubusercontent.com/61674328/103168717-89c72980-4870-11eb-92bc-31d8b7632fb4.png)
图6
![image](https://user-images.githubusercontent.com/61674328/103168721-99df0900-4870-11eb-8c4f-840c160ea41b.png)

**Comment by DaanV2** [comment]
Could you send a text copy of the error shown in figure 2?

您可以发送图2所示错误的文本副本吗？

**Comment by lchzh3473** [comment]
> Could you send a text copy of the error shown in figure 2?
> 
> 您可以发送图2所示错误的文本副本吗？


[vscode-inno-updater-1609064165.log](https://github.com/Blockception/VSCode-Bedrock-Development-Extension/files/5744434/vscode-inno-updater-1609064165.log)

**Comment by DaanV2** [comment]
Version 1.5.18 of the plugin now has compressed JSON files that might help against this issue. if issues still occur, recommended to change the installation folder.

该插件的版本1.5.18现在具有压缩的JSON文件，可能有助于解决此问题。 如果仍然出现问题，建议更改安装文件夹。
