### ISSUE TITLE
minecraft:damage_sensor linting appears incorrect

### ISSUE THREAD

**Issue by SirLich** [Blockception/VSCode-Bedrock-Development-Extension#31]
**Describe the bug**
Linting error on a valid representation for `minecraft:damage_sensor`.

**To Reproduce**
1. Create a 1.16.0 format version entity
2. Add the following component
3. View error 

```jsonc
            "minecraft:damage_sensor": {
                "triggers": {
                    "on_damage": {
                        "filters": {}
                    },
                    "deals_damage": false
                }
            }
```

**Expected behavior**
No error on correctly formatted component.

**Screenshots**
![image](https://user-images.githubusercontent.com/18729296/103469098-c0191300-4d60-11eb-93dd-b4fa5aaf7075.png)

**Comment by DaanV2** [comment]
Hey

I am unable to reproduce this, I am unsure if this is caused by my plugin. As with tests and looking at the schema itself looks like it does support array/object components,

[The damage_sensor file](https://github.com/Blockception/Minecraft-bedrock-json-schemas/blob/f1ba7b2f1f0a6b74fb82ce9f020151441bfba29a/behaviour/entities/1.16.0/components/minecraft.damage_sensor.json)

![image](https://user-images.githubusercontent.com/2393905/103469311-7120ad00-4d63-11eb-83d6-bb475e26f6b9.png)

**Comment by SirLich** [comment]
I am on 1.3.22
![image](https://user-images.githubusercontent.com/18729296/103475758-5a547780-4db0-11eb-9cd0-918461da3d74.png)

Here is the full entity, and a screenshot for viewing errors:
```jsonc
{
    "minecraft:entity": {
        "format_version": "1.16.0",
        "description": {
            "identifier": "sirlich:box",
            "is_summonable": true,
            "is_spawnable": true,
            "is_experimental": false
        },
        "components": {
            "minecraft:type_family": {},
            "minecraft:damage_sensor": {
                "triggers": {
                    "on_damage": {
                        "filters": {}
                    },
                    "deals_damage": false
                }
            },
            "minecraft:health": {
                "value": 1,
                "max": 1
            },
            "minecraft:knockback_resistance": {
                "value": 1,
                "max": 1
            },
            "minecraft:push_through": {
                "value": 1
            },
            "minecraft:collision_box": {
                "width": 1,
                "height": 1
            },
            "minecraft:physics": {}
        }
    }
}
```
![image](https://user-images.githubusercontent.com/18729296/103475769-6f310b00-4db0-11eb-98dc-ac68e12f5b1e.png)

**Comment by DaanV2** [comment]
aah I see, yeah it working as intended xD

However your format_version is in the wrong place

```json
{
  "minecraft:entity": {
    "format_version": "1.16.0",
```

Should be
```json
{
  "format_version": "1.16.0",
  "minecraft:entity": {
```

However that it didn't report that is also a problem :P

**Comment by SirLich** [comment]
Format version can go in both places, afaik
