### ISSUE TITLE
[Feature request] Add support for 'experimental features'

### ISSUE THREAD

**Issue by r4isen1920** [Blockception/VSCode-Bedrock-Development-Extension#311]
**Is your feature request related to a problem? Please describe.**
I make content not solely for the Marketplace only, thus giving me full freedom to whatever add-on I want to create as I wish. This includes being able to use experimental features that may not be included in a stable release or perhaps cannot be used for a Marketplace content. With this request in mind, I want full freedom of usage - with no validation errors - even on experimental features that actually work just fine in-game.

**Describe the solution you'd like**
Similarly to how you guys have added an option to enable "Education Edition" to support education edition terms, add another toggle where we can enable or disable the "Experiments" feature for us to utilize should we need it.

**Describe alternatives you've considered**
I just ignore the false errors related to usage of experimental features. That's just about it.

**Additional context**
![Cannot use "run_command" feature on events for example](https://user-images.githubusercontent.com/43404913/150441293-5f5eaf2e-b774-471e-8283-acd7e8480e89.png)
*Well I honestly couldn't find any more samples but the point here is that we should have more control over these things as well.*

**Comment by DaanV2** [comment]
I'm sorry, I cannot add support for experimental. Mostly for two reasons:

The plugin is built around the idea of supporting marketplace-ready content. Therefore, it avoids experimental/beta/undocumented features unless vanilla files have been seen implementing it. This thought should avoid situations where everyone starts using features. Minecraft either then fixes it or removes it, which causes developers longer developing times or discarding content.

It also goes that supporting experimental increases the workload of maintaining by a lot.
