### ISSUE TITLE
Skeleton behaviors don't validate (filters)

### ISSUE THREAD

**Issue by SirLich** [Blockception/VSCode-Bedrock-Development-Extension#35]
**Describe the bug**
Vanilla Behavior file for Skeleton doesn't validate as error-free. Could technically be an issue in the code, but I somehow doubt it. Its filters, so... yeah, nested nastiness to validate.

**To Reproduce**
1) Open VSCode with the plugin installed
2) Open the Skeleton behavior pack entity file

**Expected behavior**
No errors on vanilla entities 

**Screenshots**
![image](https://user-images.githubusercontent.com/18729296/104073444-fac1f600-520d-11eb-9d6f-d695c361f31f.png)

**Desktop (please complete the following information):**
Windows

**Comment by DaanV2** [comment]
This is apparently an old format of filters that is not really supported. I have thus decided to not add support for it. :)
