### ISSUE TITLE
The "sounds" property in sounds.json

### ISSUE THREAD

**Issue by Nusiq** [Blockception/VSCode-Bedrock-Development-Extension#36]
**Describe the bug**
The json schema for `sounds.json` accepts the "sounds" key in `interactive_sounds/block_sounds/<block>/events/fall/sounds`.

**To Reproduce**
1. Create sounds.json file with `interactive_sounds/block_sounds/<block>/events/fall/sounds` JSON path in it.
2. See that the "sounds" property isn't highlighted as an error.

**Expected behavior**
The "sounds" property should be highlighted as an error and there should be no hint for adding it to the file.

**Screenshots**
A screenshot from vanilla RP which suprisingly uses this invalid key:
![obraz](https://user-images.githubusercontent.com/34062025/104128462-9616b080-535f-11eb-8e05-c4acbf6740e7.png)

**Additional context**
This mistake was easy to make bacause the property does  does apear in the vanilla Minecraft resource pack `sounds.json` file but it has no effect on the game and almost certainly is a bug.

You can verify that replacing "sounds" with "sound" in default resource pack does actually add new sounds to the game
(it's especially easy to hear when you test the "soul_sound" fall sound).

**Comment by DaanV2** [comment]
Waiting for a response from ms as default vanilla files use both

**Comment by DaanV2** [comment]
Official word is that `sound` is supported
