### ISSUE TITLE
Molang color coding in json strings doesn't work

### ISSUE THREAD

**Issue by bernie-g** [Blockception/VSCode-Bedrock-Development-Extension#373]
**Describe the bug**
It seems that molang color coding in jsons doesn't work. The schema is matched and autocompletion for molang works great, just seems that the color coding doesn't work. My friend was able to reproduce the same thing.

**To Reproduce**
To reproduce, create a resource pack entity animation json in a valid folder where the schema is applied, and use this json:
```json
{
    "format_version": "1.12.0",
    "animations": {
        "animation.test": {
            "bones": {
                "test":{"position": ["variable.test = math.cos(5);", "0", "0"]}
            }
        }
    }
}
```

**Screenshots**
![](https://i.geckolib.com/file/softwarelocker/6vLjbT.png)

- VSCode version: 1.69.1
- Blockception version: v4.0.12
- OS: Windows 10

**Comment by bernie-g** [comment]
Hm, it looks like it's dependent on the theme. Not sure if this is the theme's fault or the plugins.

**Comment by DaanV2** [comment]
What is the filename and filepath?

**Comment by bernie-g** [comment]
> What is the filename and filepath?

`test_rp/animations/test.animation.json`. Either way, it's not the file path. It seems to break depending on the theme; for example it works on `Dark+` but not `Dark`, both of which are builtin VS Code themes I believe.

**Comment by DaanV2** [comment]
Yeah, but that a problem of Dark, its doesn't define the colours of things like classes, structs and many more types as such. I also cant change that behavior
