### ISSUE TITLE
"on_entry" and "on_exit" properties not supported for animation_controllers within Resource Packs

### ISSUE THREAD

**Issue by CodeZea1ot** [Blockception/VSCode-Bedrock-Development-Extension#39]
**Describe the bug**
`"on_entry"` and `"on_exit"` are considered illegal properties within a Resource Pack `animation_controller`

**To Reproduce**
1. Open an animation_controller that is contained within a Resource Pack
2. Attempt to add an `"on_entry"` and/or `"on_exit"` property to a state. 
3. Receive error highlighting and hover message, stating that these are invalid properties.

**Expected behavior**
Support for `"on_entry"` and `"on_exit"` properties within Resource Pack `animation_controllers`

**Screenshots**
![on_entry](https://user-images.githubusercontent.com/54991101/107428425-9cc84d00-6af0-11eb-9645-5d7282cfe21b.PNG)

**Comment by DaanV2** [comment]
Should be added now :)
