### ISSUE TITLE
Error: Matches multiple schemas when only one must validate.

### ISSUE THREAD

**Issue by MetalManiac1331** [Blockception/VSCode-Bedrock-Development-Extension#41]
**"Matches multiple schemas when only one must validate." error appears on working behavior pack manifeste manifests in add-ons**
When I finish my manifest for a Behavior Pack of an Add-On, I get this error:
```json
{
	"resource": "/c:/Users/<user>/Documents/addons/WOM/bp/manifest.json",
	"owner": "_generated_diagnostic_collection_name_#0",
	"severity": 4,
	"message": "Matches multiple schemas when only one must validate.",
	"startLineNumber": 1,
	"startColumn": 1,
	"endLineNumber": 1,
	"endColumn": 2
}
```
Everything works perfectly in-game.

**To Reproduce**
1. Create an Add-On scheme
2. Create the Ressources Pack and Behavior Pack manifest, version 2.
3. See the error

**Screenshot**
![image](https://user-images.githubusercontent.com/64897248/108482951-6df16a00-729a-11eb-80eb-79fb39ad8e2c.png)

**Comment by DaanV2** [comment]
I have checked this manifest and checked the validation, but the error getting returned. Is not part of my JSON validation scheme, is it possible you are using multiple extension or settings that use validation?

If you disable my plugin and the error remains, then it's a different plugin.

**Comment by MetalManiac1331** [comment]
Indeed it was, it came from a rubbish pack I thought I had uninstalled, sorry...

**Comment by DaanV2** [comment]
Np, It always good to be sure
