### ISSUE TITLE
Schema is partially incorrect for the minecraft:entity_sensor component

### ISSUE THREAD

**Issue by Pszemis** [Blockception/VSCode-Bedrock-Development-Extension#42]
**Describe the bug**
Schema is partially incorrect for the minecraft:entity_sensor component

**To Reproduce**
1. Add the component
2. Add the "event" parameter
3. The suggested formating will be:

"event": {
 "event": name,
 "target": target
}

**Expected behavior**
The suggested formatting should be:

"event": name

Tested on Minecraft version 1.16.210

**Comment by DaanV2** [comment]
Fixed
