### ISSUE TITLE
Autocomplete shouldnt trigger on enter in .mcfunction files AND .lang files

### ISSUE THREAD

**Issue by Scaietele** [Blockception/VSCode-Bedrock-Development-Extension#427]
**Describe the bug**
When pressing the Enter key to add a newline to a `.mcfunction` file, it keeps displaying a dropdown for autocomplete.

**To Reproduce**
1. Create a new `.mcfunction` file in the project or locate an existing `.mcfunction` file.
2. Press the Enter key to go to a new line
3. A dropdown is automatically displayed
4. If I press Enter again it selects the first value in the dropdown and auto-completes it
5. If I press Enter repeatedly I end up with something like this:
```
alwaysday
alwaysday
alwaysday
alwaysday
alwaysday 
```
Since `alwaysday` is the first value in the dropdown menu.

**Expected behavior**
When pressing Enter to introduce a new line it should not display any dropdown menu.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser chrome
 - Version v4.1.30

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**EDIT:**
Same behaviour happens with `.lang` files. I am unable to add multiple empty lines by repeatedly pressing the Enter key. I have to press Enter, then press Escape in order to get rid of the dropdown menu, then press Enter again to add a new line and repeat the process.

**Comment by DaanV2** [comment]
hmm, hitting enter on auto-complete is default behaviour for vscode completion, need to rethink
