### ISSUE TITLE
Function reference navigation breaks after execute

### ISSUE THREAD

**Issue by Joeyrsp** [Blockception/VSCode-Bedrock-Development-Extension#44]
**Describe the bug**
The path of the function in a function command can be navigated through to get to the referenced function. This breaks when an execute clause is present before the function call.

**To Reproduce**
1. create 2 function files a.mcfunction and b.mcfunction
2. add `function b` to a.mcfunction
3. ctrl-click function path to navigate to b.mcfunction
4. replace `function b` with `execute @a ~ ~ ~ function b`
5. ctrl-click function path and fail to navigate to b.mcfunction 

**Expected behavior**
Function path is navigable

 - Version: v1.7.1

**Comment by DaanV2** [comment]
Fixed and ready for next update
