### ISSUE TITLE
Exclude files/folders

### ISSUE THREAD

**Issue by x-2mas** [Blockception/VSCode-Bedrock-Development-Extension#46]
In my workspace, I have a collection of sample packs (including Vanilla resource/behavior packs) that I like to reference during development. However, this extension works across every bedrock-related file in my workspace making it difficult to use extension features in the specific project I'm working on. In my case,
- Code-completion fetches objectives, entities, etc defined in every pack in the workspace
- Error/warnings are generated from every pack in the workspace
- Causes performance issues when there are a lot of other packs or previous projects in the workspace

Having an option to exclude files/folders from the extension (similar to .gitignore or files.exclude) will effectively solve these problems.

**Comment by DaanV2** [comment]
https://github.com/Blockception/VSCode-Bedrock-Development-Extension/blob/main/documentation/project/MCIgnore.md
