### ISSUE TITLE
Typings - not working

### ISSUE THREAD

**Issue by LynxLeader** [Blockception/VSCode-Bedrock-Development-Extension#464]
The typings are not working on my packs.
ive reinstalled it many times and its still not working
and ive tried to use it on JSON files and Functions and it still will not show the typings.

please let me know if this is a bug, or something i can fix.

**Comment by DaanV2** [comment]
You can check this guide:

https://github.com/Blockception/VSCode-Bedrock-Development-Extension/blob/main/documentation/Json%20Validation.md
Might be that the extension doesn't regonizes paths

If not, check for any errors in the console:
https://faq.blockception.dev/vscode-extension-mcbe/console

**Comment by LynxLeader** [comment]
There seems to be no issues with the console, and i also moved the project file to my desktop and made sure all the paths were correct, im still having issues

**Comment by DaanV2** [comment]
Are there manifest files?
or can you share the project?

**Comment by LynxLeader** [comment]
its just an empty behavior folder, it only has a manifest and a empty entities folder. all i did is, i created a new entity and i started to write it and no typings are showing up. even when i download the vanilla behaviors i still see no typings

**Comment by DaanV2** [comment]
Can you show the output of the console?

**Comment by DaanV2** [comment]
Is it seeing the typing for the manifest file?

**Comment by LynxLeader** [comment]
no its not

**Comment by DaanV2** [comment]
Then I really have no idea, might be some settings not correct in your vscode.
By all accounts it should just work.
