### ISSUE TITLE
Default render controllers are invalid.

### ISSUE THREAD

**Issue by JannisX11** [Blockception/VSCode-Bedrock-Development-Extension#47]
When using a default render controller that exists in the vanilla resource pack, for example `"controller.render.default"`, it is marked as invalid.

**To Reproduce**
1. Create a client entity file.
2. Use the render controller "controller.render.default"
3. Error message appears "Cannot find resource controller: controller.render.default"

**Expected behavior**
These render controllers work in game and should be recognized.

**Comment by DaanV2** [comment]
This is an issue whereby the default vanilla data needs to be extended. currently that is not yet supported, but is definitely planned
