### ISSUE TITLE
Some descriptions not showing up on hover in Windows 11

### ISSUE THREAD

**Issue by b0ri5** [Blockception/VSCode-Bedrock-Development-Extension#475]
**Describe the bug**
Hover descriptions do not show up on some entity json files. As far as I can tell the problem is with Windows 11 since two computers with Windows 11 have the issue but a computer with Windows 10 does not.

**To Reproduce**
1. Follow https://learn.microsoft.com/en-us/minecraft/creator/documents/behaviorpack and get to the cow.json step.
2. Open an manifest.json file and hover over the "description" field and observe that a Description popup shows up
3. Now open the `entities/cow.json` and hover over the first `"last_hit_by_player"` and observe a tip showing up. Move to the left and hover over `"on_death"`.
4. Observe that nothing pops up.
5. Do the above for a Windows 10 machine and observe a description like
    
    > On Death
    >
    > A molang expression ...

**Expected behavior**
The expected description shows up when hovering over JSON fields.

**Screenshots**
I can get a screenshot if that helps but hopefully the above is clear enough.

**Desktop (please complete the following information):**
 - OS: Windows 11 when it doesn't work, Windows 10 when it does
 - Both running Visual Studios Code 1.80.1 with Bedrock Definitions v2.0.8 and Blockception's Minecraft Bedrock Development v6.1.2 extensions installed.

**Additional context**
I have programming experience and am happy to help debug if that would help.

**Comment by b0ri5** [comment]
Thanks a lot for the quick fix and release. As far as I can tell it works just fine now on our Windows 11 machines.

**Comment by DaanV2** [comment]
Np ☺️ !
