### ISSUE TITLE
"should_update_effects_offscreen" does not accept booleans

### ISSUE THREAD

**Issue by JannisX11** [Blockception/VSCode-Bedrock-Development-Extension#48]
**Describe the bug**
"should_update_effects_offscreen" in the scripts section in client entity files does not accept booleans.

**To Reproduce**
1. Set scripts/should_update_effects_offscreen to true
2. true is marked as invalid because it is not a string

**Expected behavior**
"should_update_effects_offscreen" and "should_update_bones_and_effects_offscreen" should accept booleans.

**Comment by DaanV2** [comment]
The only time I have found it was in `minecraft:minecart` and there it was used as a string, 

Did you test it? then ill happly add it :)

**Comment by DaanV2** [comment]
Jannis confirmed that it works :)
