### ISSUE TITLE
Bug/Title

### ISSUE THREAD

**Issue by KinectTheUnknown** [Blockception/VSCode-Bedrock-Development-Extension#494]
**Describe the bug**
When using the fill command in a .mcfunction file, using `0` for the block state marks the command as unrecognized syntax.
Message: `Unknown syntax for: "fill" mc[minecraft.commands.fill.syntax](https://github.com/Blockception/Minecraft-Error-Codes/blob/main/minecraft/commands/fill/syntax.md)`

**To Reproduce**
`functions/foo.mcfunction`
```
# okay
fill ~ ~ ~ ~ ~ ~ minecraft:air 
fill ~ ~ ~ ~ ~ ~ minecraft:air []

# error
fill ~ ~ ~ ~ ~ ~ minecraft:air 0
```

**Expected behavior**
The extension should recognize the error case as valid syntax

**Desktop (please complete the following information):**
 - OS: Win 11
 - Browser: N/A
 - Version: 23H2

**Smartphone (please complete the following information):**
 - Device: N/A
 - OS: N/A
 - Browser: N/A
 - Version: N/A

**Additional context**
Haven't tested the fill command in other places where commands are validated.
Running on Minecraft 1.20.51.01.

**Comment by DaanV2** [comment]
Not actually bug but intended behavior ☺️ 

Minecraft, at some point, deprecated the tile data field, making the 0 invalid.
