### ISSUE TITLE
format_version fields flagging zeroes

### ISSUE THREAD

**Issue by x-2mas** [Blockception/VSCode-Bedrock-Development-Extension#50]
[![Screenshot-2021-05-08-011946.png](https://i.postimg.cc/3J8cXy8T/Screenshot-2021-05-08-011946.png)](https://postimg.cc/5jrg12Q7)
The extension is reporting errors whenever a zero is added in the format version field.

Is this a bug? or am I doing something wrong?

**Comment by DaanV2** [comment]
A fix is uploading
