### ISSUE TITLE
Numbers are not supported as blend values

### ISSUE THREAD

**Issue by JannisX11** [Blockception/VSCode-Bedrock-Development-Extension#51]
**Describe the bug**
Blend values for animations currently only support molang strings. Directly setting a number throws an error. This applies to `scripts.animate` in entity files as well as `animations` in animation controllers.

**To Reproduce**
1. Create an animation controller with something like this in one of the states:
```json
"animations": [
  {"offset_x": 15}
]
```
2. The `15` will be marked as incorrect type

**Expected behavior**
Numbers should be supported

**Additional context**
As an example, I often use this to define an offset without creating individual animations. The "offset_x" animation essentially just offsets a bone by one unit, but with the blending you can essentially set it to any value.
```json
	"animation.foo.offset_x": {
		"loop": true,
		"bones": {
			"root": {
				"position": [1, 0, 0]
			}
		}
	}
```

**Comment by DaanV2** [comment]
Hmm by their documentation, pretty sure it outdated though it only accepts string and objects

```json
array "animations" : opt
{
string ""
object ""
{
molang ""
}
}
```

So Im going to post a question towards Microsoft, cause this might be either a bug or intended feature

**Comment by DaanV2** [comment]
Confirmed that it is indeed intented

**Comment by DaanV2** [comment]
Coming to 2.0.0
