### ISSUE TITLE
Add similar thing to render controller as ACs

### ISSUE THREAD

**Issue by Xterionix** [Blockception/VSCode-Bedrock-Development-Extension#532]
**Is your feature request related to a problem? Please describe.**
Annoying to see which render controller is being used where

**Describe the solution you'd like**
Similar to this
![image](https://github.com/Blockception/VSCode-Bedrock-Development-Extension/assets/72647213/529ba7e3-5ef2-4b8f-87c5-9b2843ba3da9)

**Describe alternatives you've considered**
Manually searching

**Comment by Xterionix** [comment]
If you could point me in the direction, maybe I could implement this?

**Comment by Xterionix** [comment]
Can be closed; it's been resolved. Not sure when though

**Comment by DaanV2** [comment]
Aah did a refactor of the code lens a little while ago
