### ISSUE TITLE
RP animation autocomplete doesn't work in subdirectories

### ISSUE THREAD

**Issue by Nusiq** [Blockception/VSCode-Bedrock-Development-Extension#54]
**Describe the bug**
It looks like the plugin doesn't treat the animation files in sub-directories as animations. There is no autocomplete.

**To Reproduce**
1. Create an animation file in in your projecti n `resource_packs/<pack-name>/animations`
2. Start typing random properties used in animation to see if there is an autocomplete
3. Move the file to subdirectory `resource_packs/<pack-name>/animations/test`
4. Try writing to the file again (there is no autocomplete)

**Expected behavior**
Subdirectories are and have always been supported by Minecraft packs, the plugin should also accept them.

**Additional context**
Other pack objects also can use subdirectories. Here is a short list in case the blockception plugin also doesn't support them (i didn't check). It's not a full list but its probably safe to assume that subdirectoreis are supported everywhere, that's just a list of folders that use subdirectories on a project that I'm currently working on:
- `behavior_packs/<pack name>/items`
- `behavior_packs/<pack name>/loot_tables`
- `behavior_packs/<pack name>/animation_controllers`
- `behavior_packs/<pack name>/animations`
- `behavior_packs/<pack name>/entities`
- `behavior_packs/<pack name>/spawn_rules`
- `behavior_packs/<pack name>/trading`
- `resource_packs/<pack name>/entity`
- `resource_packs/<pack name>/animations`
- `resource_packs/<pack name>/animation_controllers`
- `resource_packs/<pack name>/items`
- `resource_packs/<pack name>/models/entity`
- `resource_packs/<pack name>/particles`
- `resource_packs/<pack name>/render_controllers`

**Comment by DaanV2** [comment]
Tested this myself and only materials seem to be unable to do subdirectories

**Comment by DaanV2** [comment]
Updated all patterns
