### ISSUE TITLE
Dynamic autocomplete

### ISSUE THREAD

**Issue by Xterionix** [Blockception/VSCode-Bedrock-Development-Extension#551]
Found these, and they work pretty fast for my 4000 line files
https://github.com/nidu/vscode-copy-json-path
https://github.com/MaloPolese/copy-json-path/tree/main/src
Hopefully helps to figure out how to do the JSON paths so it can be implemented here too.
If you can setup something with these, I'd be more than happy to contribute to make sure it covers every aspect. So like if you can set it up for one component, I'd just follow that syntax and add it for the rest

**Comment by DaanV2** [comment]
👍 

Got ideas allready for them, just need to make that code setup :)

**Comment by Xterionix** [comment]
Alr, do @ me whenever you get that done. Dynamic autocomplete is my primary reason for returning to bridge.
