### ISSUE TITLE
New gif animations for the front page

### ISSUE THREAD

**Issue by DaanV2** [Blockception/VSCode-Bedrock-Development-Extension#56]
New gif animations for the front page

**Comment by MetalManiac1331** [comment]
I could help if I new the front page of what... VSC?

**Comment by DaanV2** [comment]
Its replacing this imagine

https://github.com/Blockception/VSCode-Bedrock-Development-Extension/blob/main/documentation/resources/overview.gif

Which goes on the front page of the marketplace readme page, and the plugins readme page
