### ISSUE TITLE
say and tell commands not recognized as valid

### ISSUE THREAD

**Issue by sparks0** [Blockception/VSCode-Bedrock-Development-Extension#57]
**Describe the bug**
Typing say or tell as the first part of a line inside an mcfunction file causes the error 'Unknown command syntax: "say hello"mcfunction(mcfunction.syntax.unknown)'

**To Reproduce**
1. Create a new .mcfunction file in a behavior pack.
2. Type "say hello" on the first line

**Expected behavior**
No syntax error appears in the mcfunction file

**Screenshots**
![Screenshot_1](https://user-images.githubusercontent.com/11044584/122744140-01a66780-d288-11eb-856a-c3bd82efddb2.png)
![Screenshot_2](https://user-images.githubusercontent.com/11044584/122744141-01a66780-d288-11eb-977b-f2a97bfe5921.png)
![Screenshot_3](https://user-images.githubusercontent.com/11044584/122744142-023efe00-d288-11eb-978a-1ab4fbe73a44.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 2.1.12

**Comment by DaanV2** [comment]
Should be fixed in 2.1.14
