### ISSUE TITLE
Commands aren't running

### ISSUE THREAD

**Issue by Xterionix** [Blockception/VSCode-Bedrock-Development-Extension#582]
**Describe the bug**
Commands aren't running

**To Reproduce**
1. Open a project
2. Control + P
3. Click any of the blockception commands

**Expected behavior**
Command runs

**Screenshots**
![image](https://github.com/Blockception/VSCode-Bedrock-Development-Extension/assets/72647213/bb206871-0b67-45d6-8cf2-eb37d01724bb)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Edge
 - Version [e.g. 22] Extension or browser?

**Additional context**
- None of the other extension features appear to be working either like the json schema

**Comment by DaanV2** [comment]
Could you add the terminal? cause it all work for me 🤔 

https://faq.blockception.dev/vscode-extension-mcbe/console

**Comment by Xterionix** [comment]
Well, I switched projects and when I switched back it worked so I guess this can be closed.

**Comment by DaanV2** [comment]
Might be that it wasn't activated yet, all those things sound like it saw no reason to start yet 🤔

**Comment by Xterionix** [comment]
Same project and this time it must've activated, I guess. Shouldn't running a command be enough of a trigger for it to start?

**Comment by DaanV2** [comment]
Most of them do
