### ISSUE TITLE
Feature/Request: Dynamic autocomplete in lang

### ISSUE THREAD

**Issue by Xterionix** [Blockception/VSCode-Bedrock-Development-Extension#587]
1. **Is your feature request related to a problem? Please describe.**
No
**Describe the solution you'd like**
If I have an entity called 'bob:sometihng' suggest entity.bob:sometihng.name in the .lang
**Describe alternatives you've considered**
Manually adding it

**Comment by DaanV2** [comment]
Should be a command that creates language files that also fills them with all possible keys, 

But dynamic completion could still be useful 🤔

**Comment by Xterionix** [comment]
Unless it can fill it in while keeping my organization and current keys, I don't think it'd be that helpful.

**Comment by DaanV2** [comment]
I think it just appends missing keys 🤔 Would have to check that code again

**Comment by DaanV2** [comment]
Yeah it just appends all missing keys:
https://github.com/Blockception/VSCode-Bedrock-Development-Extension/blob/main/server/src/Lib/Commands/Language/AddAll.ts

**Comment by Xterionix** [comment]
Ah it already tracks missing stuff, wouldn't be that hard to then use that to add them to the autocomplete then?

**Comment by DaanV2** [comment]
> Ah it already tracks missing stuff, wouldn't be that hard to then use that to add them to the autocomplete then?

No shouldn't be to hard.

**Comment by DaanV2** [comment]
Added
