### ISSUE TITLE
Unknown command syntax: setmaxplayers <maxPlayer>

### ISSUE THREAD

**Issue by notDecay** [Blockception/VSCode-Bedrock-Development-Extension#59]
Uh something wrong while I wrote this: `setmaxplayer 2`.
The error says: Unknown command syntax: "setmaxplayers 4"mcfunction(mcfunction.syntax.unknown)

Screenshot
![bug](https://user-images.githubusercontent.com/88096038/127639547-67c2c8c4-9718-4c35-b33b-dd8027cea3c6.png)

(Syntax you can find here: https://minecraft.fandom.com/wiki/Commands/setmaxplayers)

**Comment by DaanV2** [comment]
Added it in
