### ISSUE TITLE
No support for code indentation in .lang files

### ISSUE THREAD

**Issue by Nusiq** [Blockception/VSCode-Bedrock-Development-Extension#6]
**Describe the bug**
Syntax highlighting for .lang files doesn't support indentation.

**To Reproduce**
Paste this code to your .lang file.
```
normal.key=Hello
other.key=Other value

    this.is.intersesting=Wow! That's a lot of errors
```

**Expected behavior**
Not getting errors. This is a valid file.

**Screenshots**
![obraz](https://user-images.githubusercontent.com/34062025/95685065-24568b80-0be5-11eb-84d1-f394f308e324.png)

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by DaanV2** [comment]
Is the problem present in version 1.0.2?

I noticed it myself and uploaded a patch, but I'm unsure if it reached you in time.

**Comment by Nusiq** [comment]
Seems to be working now. Thanks.

**Comment by DaanV2** [comment]
I think I uploaded the new version at the moment you reported the issue.

Still always good to have people reporting problems! 👍
