### ISSUE TITLE
A small bug: tripwire block id is not supported

### ISSUE THREAD

**Issue by Venderbad** [Blockception/VSCode-Bedrock-Development-Extension#60]
**Describe the bug**
A small bug. This extension does not recognise block id "tripwire". There might be more than just one bug like this, I guess.

**To Reproduce**
1. Create an empty .mcfunction file
2. Open the file with VSCode and type in this sample: execute @e ~ ~ ~ detect ~ ~ ~ tripwire 3 setblock ~ ~ ~ web
4. See warning: No known block found with the id: "tripwire"

**Appendix**
<img width="673" alt="bug" src="https://user-images.githubusercontent.com/70248957/127815395-073a3cf9-e51d-408a-9564-0ff75353c95b.png">

**Comment by DaanV2** [comment]
Its written as tripWire for some reason, adjusting it now
