### ISSUE TITLE
Bug/Missing spectator gamemode

### ISSUE THREAD

**Issue by drav0011** [Blockception/VSCode-Bedrock-Development-Extension#608]
**Describe the bug**

**To Reproduce**
1. Create an mcfunction file in a project
2. Add the following line `gamemode spectator @a`
3. Extension will show `minecraft.mode.gamemodes.invalid`

**Expected behavior**
gamemode spectator should not be marked as an error

**Screenshots**
![image](https://github.com/Blockception/VSCode-Bedrock-Development-Extension/assets/43525295/730c4bed-8d8e-426e-ab09-bb0197a800e6)

**Desktop (please complete the following information):**
 - OS: Windows 11

**Additional context**
None

**Comment by DaanV2** [comment]
Found the bug, its was looking for `spectator ` with a space at the end T.T
