### ISSUE TITLE
Feature/Request: Setting to disable json autocompletion

### ISSUE THREAD

**Issue by Xterionix** [Blockception/VSCode-Bedrock-Development-Extension#615]
**Describe the solution you'd like**
A setting to disable all completions like the one that already exists in the .lang file

Personal preference mainly, but it may be handy for someone else. If you'll point me in the right direction, I'd be happy to implement this.

**Comment by DaanV2** [comment]
The settings interface can be found here:

https://github.com/Blockception/VSCode-Bedrock-Development-Extension/blob/main/server/src/lib/Server/Settings/Settings.ts

Which mirrors this configuretion:

https://github.com/Blockception/VSCode-Bedrock-Development-Extension/blob/85ac901f1914d1bab4d95a106f65b12a5375b23e/package.json#L104

Here the call is made and managed to determine who/what/where to do with json completion

https://github.com/Blockception/VSCode-Bedrock-Development-Extension/blob/85ac901f1914d1bab4d95a106f65b12a5375b23e/server/src/lib/completion/minecraft/json/document.ts#L15C8-L15C9
