### ISSUE TITLE
"scriptevent" command is not recognized when run by an execute

### ISSUE THREAD

**Issue by Scaietele** [Blockception/VSCode-Bedrock-Development-Extension#622]
**Describe the bug**
The "scriptevent" command is not recognized and shows up with squigly lines in .mcfunction files when run by an execute command

**To Reproduce**
1. in a new .mcfunction file or an existing one create a new "scriptevent" command used for scripting
ex: `execute as @s at @s run scriptevent this:that`
2. see that "scriptevent" is not recognized and has squigly lines under it

**Expected behavior**
No squigly lines and no errors should show up.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - IDE: Visual Studio Code 1.91.1

**Comment by DaanV2** [comment]
If I got it right, I have added the command in the latest release 😄

**Comment by Xterionix** [comment]
Yeah, the command is there now. This can be closed now.
