### ISSUE TITLE
Request: Support `if blocks` syntax

### ISSUE THREAD

**Issue by SuperScript-PRC** [Blockception/VSCode-Bedrock-Development-Extension#625]
I found that the extension didnt support this syntax (`execute ... if blocks x y z x1 y1 z1 x2 y2 z2 <masked|all>`) :
![image](https://github.com/user-attachments/assets/7f7a3dce-984b-4a17-aebb-675af5ce69ba)
but these syntaxes are all supported in MCBE cmd system.
Hope it can be supported, thks dev :)

**Comment by DaanV2** [comment]
Found it, made that specific syntax block instead of blocks
