### ISSUE TITLE
Generate packs with wrong Filename

### ISSUE THREAD

**Issue by SnowFox4004** [Blockception/VSCode-Bedrock-Development-Extension#631]
**Describe the bug**
When creating a new pack, it will generate the manifest.json.However, the name of the file is manifest..json, it's such a hard work to find it wrong
![image](https://github.com/user-attachments/assets/d724a211-3769-4fd3-a137-d6167e91a192)

**To Reproduce**
run `create a new resource/behavior pack` command in welcom page of the extension

**Expected behavior**
simple generate right file

**Screenshots**
you can see above

**Desktop (please complete the following information):**
 - OS: Windows10
 - Browser N/A
 - Version idk

**Comment by DaanV2** [comment]
Thanks for the report!, I applied a fix and it should roll out in a while
