### ISSUE TITLE
fileMatch patterns for some JSON Schema are too permissive

### ISSUE THREAD

**Issue by AdamodeOne** [Blockception/VSCode-Bedrock-Development-Extension#680]
**Describe the bug**
In `package.json` at `contributes/jsonValidation`, the `fileMatch` patterns for some JSON schema are too permissive. By this, I mean that the schema applies to files which it should not apply.

For example,  this is the entry for a resource pack entity:
```
{
        "fileMatch": [
          "entity/*.{json,jsonc,json5}",
          "entity/**/*.{json,jsonc,json5}",
          "*.{entity.rp,e.rp,ce,rpe,actor,entity}.{json,jsonc,json5}",
          "!models/entity/**/*.{json,jsonc,json5}",
          "!models/entity/*.{json,jsonc,json5}"
        ],
        "url": "./minecraft-bedrock-schemas/resource/entity/entity.json"
}
```
As can be see, this means that it applies to _any_  JSON file within a folder called `entity`. Compare this to the entry for a resource pack item:
```
{
        "fileMatch": [
          "resource_packs/*/items/*.{json,jsonc,json5}",
          "*resource*pack*/items/*.{json,jsonc,json5}",
          "*Resource*Pack*/items/*.{json,jsonc,json5}",
          "*RP*/items/*.{json,jsonc,json5}",
          "*rp*/items/*.{json,jsonc,json5}",
          "resource_packs/*/items/**/*.{json,jsonc,json5}",
          "*resource*pack*/items/**/*.{json,jsonc,json5}",
          "*Resource*Pack*/items/**/*.{json,jsonc,json5}",
          "*RP*/items/**/*.{json,jsonc,json5}",
          "*rp*/items/**/*.{json,jsonc,json5}",
          "*.{item.rp,i.rp,rpi,rp_item}.{json,jsonc,json5}"
        ],
        "url": "./minecraft-bedrock-schemas/resource/items/items.json"
}
```
In this case, it ensures that the `items` folder must be inside the root of a resource pack for the schema to be applied. 

This current behavior is frustrating, because we have custom schemas which apply to JSON files outside of the resource and behavior packs, but they get overridden by this extension if they are in a folder called `entity` or `attachables` or `fogs`, etc. Ideally, all of the schema should be implemented like it was in the `items` example above.

**To Reproduce**
1. Create a folder called `entity` outside a resource pack or behavior pack
2. Create a JSON file inside the folder
3. Observe that the resource pack entity schema is applied to the JSON file

**Expected behavior**
Schema should not be applied to files which are not in a resource pack or behavior pack

**Comment by ArthurGuinot** [comment]
I have observed that if the behaviorpack's name has "rp" in it (for me it was "behavior_packs/Airplanes/...", it will automatically be targeted as ressource pack because of the "*rp*/.." fileMatch. Maybe we should change priorities of the fileMatch?

**Comment by DaanV2** [comment]
no, RP it self is an indicator for whenever or it is a resource pack using community conventies
