### ISSUE TITLE
Resource pack animation controller suggestions in behaviorpack

### ISSUE THREAD

**Issue by Nusiq** [Blockception/VSCode-Bedrock-Development-Extension#7]
**Describe the bug**
Animation controllers in behavior pack and resource pack have slightly different structure.
Some of the items are valid only in RP or only in BP. For example - particle_effects are part
of the resource pack animation controller but not behavior pack.

**To Reproduce**
1. Create animation controller from this pattern inside behaviorpack:
```json
{
    "format_version": "1.10.0",
    "animation_controllers": {
        "controller.animation.test": {
            "states": {
                "default": {
                    
                }
            }
        }
    }
}
```
2. See the autocomplete list for the items in "default" state.

**Expected behavior**
The autocomplete shoud suggest - animations, on_entry, on_exit and transitions (I'm not surea about "variables" I've never seen that in bp or in rp).

**Screenshots**
![obraz](https://user-images.githubusercontent.com/34062025/95691086-fcc6e980-0c0b-11eb-9e37-6a6f796a1f05.png)

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
The JSON scheam for animation_controllers from behavior packs which was automatically generated based
on some examples of behaviorpacks: https://github.com/Nusiq/bedrock-json-schemas/blob/master/schemas/bp.animation_controller.schema.json

**Comment by DaanV2** [comment]
Hey,

I have made fixes in a new patch, can you confirm they are gone? in version 1.0.2?

**Comment by Nusiq** [comment]
Looks like it's fixed to me. Thanks.

**Comment by DaanV2** [comment]
Closing this issue since it has been fixed!

Thanks for the report 👍
